version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mongodb
    versions:
    - 3.6.4
    - 3.6.5
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: bson
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/mongodb"
    versions:
    - 3.6.3
    - 3.6.5
  - dependency-name: ws
    versions:
    - 7.4.2
